name: openai_gpt3_api
description: A wrapper for the HTTP calls to the OpenAI API for the language model GPT-3.
version: 0.2.1
homepage: 'https://github.com/morriskurz/openai_gpt3_dart_api'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.4.0

dev_dependencies:
  test: ^1.20.2
  pedantic: ^1.11.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5


